// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkerdjwnxrkiwzqklspp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZXJkandueHJraXd6cWtsc3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTk0ODEsImV4cCI6MjA3MzI3NTQ4MX0.lgCcm_jyirlfNFyb3qSkb4vZK6Ryec5DJIvDE7AFiBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});